### ISSUE TITLE
Support parameters on the path level

### ISSUE THREAD

**Issue by Manfred** [Manfred/Reynard#6]
Support something like this:

```yaml
paths:
  /users/{id}:
   parameters:
     - name: id
       in: path
```
